#!/usr/bin/env bash
# Step 70 — TBMQ broker + integration executor on the operator-managed data services,
# MQTTS L4 service with mutual TLS, X.509 device authentication, Envoy UI route, and the
# Kafka integrations that forward device detections and health reports to the app Kafka (KEDA-scaled executors).
# Idempotent: kustomize build | kubectl apply; rollouts only happen when specs change;
# REST configuration is compared before it is written.
source "$(dirname "$0")/../lib.sh"
require kubectl envsubst python3 curl jq openssl

NS=$TBMQ_NAMESPACE
step "70 tbmq: broker, MQTTS + client certs on ${MQTT_LB_IP}:8883 (L4), UI on ${EDGE_LB_IP} (L7)"
wait_api
for crd in certificates.cert-manager.io httproutes.gateway.networking.k8s.io kafkas.kafka.strimzi.io clusters.postgresql.cnpg.io; do
  crd_exists "$crd" || die "CRD $crd missing — run make install-cert-manager install-envoy-gateway install-operators first"
done
k -n "$NS" get kafka/tbmq-kafka clusters.postgresql.cnpg.io/tbmq-db statefulset/tbmq-valkey >/dev/null 2>&1 ||
  die "data services missing — run: make install-tbmq-deps"
k -n "$NS" get secret tbmq-db-app tbmq-valkey tbmq-broker tbmq-kafka-cluster-ca-cert >/dev/null 2>&1 ||
  die "secrets tbmq-db-app / tbmq-valkey / tbmq-broker / tbmq-kafka-cluster-ca-cert missing — run: make install-tbmq-deps"

OUT="$GENERATED_DIR/tbmq"
mkdir -p "$OUT"

# --- device CA (public certificate only) → config map generator input ------------
k -n cert-manager get secret iot-device-ca -o jsonpath='{.data.tls\.crt}' | base64 -d >"$OUT/device-ca.crt"
[[ -s "$OUT/device-ca.crt" ]] || die "device CA secret cert-manager/iot-device-ca missing — run: make install-cert-manager"

# --- Kafka topic replication (TBMQ hard-codes replication.factor:1 per topic) -----
KAFKA_REPLICATION_FACTOR=$((KAFKA_REPLICAS < 3 ? KAFKA_REPLICAS : 3))
KAFKA_MIN_ISR=$((KAFKA_REPLICATION_FACTOR > 1 ? KAFKA_REPLICATION_FACTOR - 1 : 1))
python3 - "$DEPLOY_DIR/tbmq/kafka-topic-properties.env" "$KAFKA_REPLICATION_FACTOR" "$KAFKA_MIN_ISR" "$OUT" <<'EOF'
import re, sys
src, rf, isr, out = sys.argv[1], int(sys.argv[2]), int(sys.argv[3]), sys.argv[4]
env = []
if rf > 1:
    for line in open(src):
        line = line.strip()
        if line and not line.startswith("#"):
            name, value = line.split("=", 1)
            value = re.sub(r"replication\.factor:\d+", f"replication.factor:{rf}", value)
            env.append((name, f"{value};min.insync.replicas:{isr}"))
for sts, fname in (("tbmq", "kafka-topics-tbmq.yaml"), ("tbmq-integration-executor", "kafka-topics-ie.yaml")):
    lines = [f"# Generated by 70-tbmq.sh: Kafka topic replication factor {rf}" + ("" if env else " (TBMQ default, no-op)"),
             "apiVersion: apps/v1", "kind: StatefulSet", "metadata:", f"  name: {sts}",
             "  namespace: thingsboard-mqtt-broker"]
    # No env list at all when nothing is overridden: an empty list in a strategic merge patch is null
    # and would delete the container's env.
    if env:
        lines += ["spec:", "  template:", "    spec:", "      containers:", "        - name: server", "          env:"]
        for name, value in env:
            lines += [f"            - name: {name}", f'              value: "{value}"']
    with open(f"{out}/{fname}", "w") as f:
        f.write("\n".join(lines) + "\n")
EOF

render "$DEPLOY_DIR/tbmq/kustomization.yaml.tpl" >"$OUT/kustomization.yaml"
render "$DEPLOY_DIR/tbmq/edge.yaml.tpl" >"$OUT/edge.yaml"
k kustomize --load-restrictor=LoadRestrictionsNone "$OUT" >"$OUT/rendered.yaml"

# Keystore password for the MQTTS certificate (cert-manager writes keystore.p12 with it).
pw_file="$STATE_DIR/tbmq-mqtt-keystore-password"
mkdir -p "$STATE_DIR"
if [[ ! -s "$pw_file" ]]; then
  existing=$(k -n "$NS" get secret tbmq-mqtt-keystore -o jsonpath='{.data.password}' 2>/dev/null | base64 -d || true)
  (umask 077 && if [[ -n "$existing" ]]; then printf '%s' "$existing"; else openssl rand -hex 24 | tr -d '\n'; fi >"$pw_file")
fi
k -n "$NS" create secret generic tbmq-mqtt-keystore --from-file=password="$pw_file" \
  --dry-run=client -o yaml | k apply -f - | sed 's/^/    /'

# JWT signing key for UI/REST tokens (TBMQ's default key is public). Created once; replacing it
# only logs out UI sessions.
if ! k -n "$NS" get secret tbmq-jwt >/dev/null 2>&1; then
  k -n "$NS" create secret generic tbmq-jwt --from-literal=signing-key="$(openssl rand -base64 64 | tr -d '\n')" >/dev/null
  ok "generated JWT signing key (secret $NS/tbmq-jwt)"
fi

# The pods mount the MQTTS certificate secret: issue it before the StatefulSet rolls.
extract_doc() { # extract_doc <file> <kind> <name>
  python3 -c '
import sys
path, kind, name = sys.argv[1:]
docs = open(path).read().split("\n---\n")
print("\n---\n".join(d for d in docs if f"kind: {kind}\n" in d and f"\n  name: {name}\n" in d))
' "$@"
}
extract_doc "$OUT/rendered.yaml" Certificate tbmq-mqtt-tls | k apply -f - | sed 's/^/    /'
k -n "$NS" wait --for=condition=Ready certificate/tbmq-mqtt-tls --timeout="${WAIT_TIMEOUT}s" >/dev/null
# An existing certificate gets keystore.p12 added without re-issuance, shortly after the spec change.
retry 120 2 k -n "$NS" get secret tbmq-mqtt-tls -o jsonpath='{.data.keystore\.p12}' --allow-missing-template-keys=false ||
  die "cert-manager did not add keystore.p12 to secret $NS/tbmq-mqtt-tls"
ok "MQTTS certificate issued (secret $NS/tbmq-mqtt-tls, with PKCS#12 keystore)"

# StatefulSets that were scaled to 0 (make down, or the legacy switch in step 60) come back
# through the replicas in the rendered manifests.
kube_apply "$OUT/rendered.yaml"

# Superseded: upstream nginx Ingress, and MQTT over WebSocket (devices must present certificates).
for obj in ingress/tbmq-ingress httproute/tbmq-mqtt-ws backendtrafficpolicy/tbmq-mqtt-ws-proxy-protocol; do
  if k -n "$NS" get "$obj" >/dev/null 2>&1; then
    k -n "$NS" delete "$obj" | sed 's/^/    /'
  fi
done

info "waiting for TBMQ rollout"
rollout "$NS" statefulset/tbmq >/dev/null
rollout "$NS" statefulset/tbmq-integration-executor >/dev/null
ok "tbmq ($TBMQ_REPLICAS) and integration executor ($TBMQ_IE_REPLICAS) ready"

lb_ip_assigned() {
  [[ "$(k -n "$NS" get svc tbmq-mqtt -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" == "$MQTT_LB_IP" ]]
}
route_accepted() { # both Accepted and ResolvedRefs must be True
  k -n "$NS" get httproute "$1" -o json | jq -e '
    [.status.parents[]?.conditions[]? | select(.type == "Accepted" or .type == "ResolvedRefs") | .status]
    | length == 2 and all(. == "True")' >/dev/null
}

retry 120 2 lb_ip_assigned || die "tbmq-mqtt did not get $MQTT_LB_IP: kubectl -n $NS describe svc tbmq-mqtt"
release_lb_node_ports "$NS" tbmq-mqtt
ok "tbmq-mqtt LoadBalancer on $MQTT_LB_IP (8883 only, no NodePorts)"
retry 120 2 route_accepted tbmq-ui || die "HTTPRoute tbmq-ui not accepted: kubectl -n $NS describe httproute tbmq-ui"
ok "HTTPRoute tbmq-ui accepted"

# --- admin password (TBMQ REST API) ---------------------------------------------------
tbmq_url="http://$EDGE_LB_IP"
if [[ -z "$TBMQ_ADMIN_PASSWORD" ]]; then # lib.sh loads an existing generated password
  (umask 077 && openssl rand -hex 16 | tr -d '\n' >"$STATE_DIR/tbmq-admin-password")
  TBMQ_ADMIN_PASSWORD=$(<"$STATE_DIR/tbmq-admin-password")
fi
export TBMQ_ADMIN_USER TBMQ_ADMIN_PASSWORD
deadline=$((SECONDS + 300))
while :; do # exit 1 = TBMQ not answering yet (rollout, Envoy 503)
  rc=0
  out=$(python3 "$ROOT_DIR/scripts/tbmq_credentials.py" admin-password --url "$tbmq_url" 2>&1) || rc=$?
  ((rc == 1 && SECONDS < deadline)) || break
  sleep 5
done
((rc == 0)) || die "TBMQ admin password: $out"
printf '%s\n' "$out" | sed 's/^/    /'
ok "admin login $TBMQ_ADMIN_USER uses a generated password (.state/tbmq-admin-password unless TBMQ_ADMIN_PASSWORD is set)"

# --- X.509 device authentication (TBMQ REST API) ------------------------------------
render "$DEPLOY_DIR/tbmq/device-credentials.json.tpl" >"$OUT/device-credentials.json"
x509() { python3 "$ROOT_DIR/scripts/tbmq_credentials.py" "$1" --url "$tbmq_url" --file "$OUT/device-credentials.json"; }
x509 ensure-x509 | sed 's/^/    /'
x509 check-x509 | sed 's/^/      /' || die "X.509 authentication still differs after the update"
ok "X.509 auth: client certificate required on 8883, CN → ACL rules from credentials 'iot-devices'"

# --- integration executor → app Kafka (TBMQ Kafka integrations) -------------------------
# TBMQ gives every integration a single-partition message topic (message order) and assigns the
# integration to one executor, so the integration count is the ceiling on executor parallelism:
# TBMQ_IE_SHARDS tunnel groups x 3 sensor positions.
PIPELINE_NS=iot-pipeline
k -n "$PIPELINE_NS" get secret tbmq-ie app-kafka-cluster-ca-cert >/dev/null 2>&1 ||
  die "app Kafka user tbmq-ie / cluster CA missing — run: make install-app-kafka"
APP_KAFKA_USERNAME=tbmq-ie
APP_KAFKA_PASSWORD=$(k -n "$PIPELINE_NS" get secret tbmq-ie -o jsonpath='{.data.password}' | base64 -d)
APP_KAFKA_CA_PEM=$(k -n "$PIPELINE_NS" get secret app-kafka-cluster-ca-cert -o jsonpath='{.data.ca\.crt}' | base64 -d)
export APP_KAFKA_USERNAME APP_KAFKA_PASSWORD APP_KAFKA_CA_PEM
((TBMQ_IE_SHARDS >= 1)) || die "TBMQ_IE_SHARDS must be >= 1 (is $TBMQ_IE_SHARDS)"
ie_count=$((TBMQ_IE_SHARDS * 3))
((TBMQ_IE_MAX_REPLICAS <= ie_count)) ||
  warn "TBMQ_IE_MAX_REPLICAS=$TBMQ_IE_MAX_REPLICAS exceeds the $ie_count integrations — the extra executors would idle"

# Topic filters of one shard: MQTT '+' matches a whole level, so a group of tunnels can only be named
# tunnel by tunnel. Shard s of S takes the tunnels with index % S == s — generated ids (T000123) in
# generator mode, the ids of SIM_PROFILES_FILE in profiles mode. S=1 keeps the wildcard of the
# unsharded layout. Devices publish detections and their own health reports; both are forwarded.
ie_topic_filters() { # ie_topic_filters <position> <shard>  — JSON array
  python3 - "$1" "$2" "$TBMQ_IE_SHARDS" "$SIM_TUNNELS" "$SIM_MODE" "$SIM_PROFILES_FILE" <<'EOF'
import json, re, sys
position, shard, shards, tunnels, mode, profiles = (
    sys.argv[1], int(sys.argv[2]), int(sys.argv[3]), int(sys.argv[4]), sys.argv[5], sys.argv[6])
suffixes = ("detections", "health")
if shards == 1:
    ids = ["+"]
elif mode == "profiles":
    text = open(profiles).read()
    all_ids = re.findall(r"^\s*-?\s*tunnel_id:\s*([A-Za-z0-9_-]+)", text, re.M)
    ids = all_ids[shard::shards]
else:
    ids = [f"T{i:06d}" for i in range(shard, tunnels, shards)]
print(json.dumps([f"tunnels/{i}/sensors/{position}/{s}" for i in ids for s in suffixes]))
EOF
}

# Renderings of an earlier shard count would otherwise be left behind for verify.sh to check.
rm -f "$OUT"/app-kafka-integration-*.json "$OUT"/integration-id-*
IE_TRIGGERS_YAML="" ie_names=()
for IE_SHARD_POSITION in start middle end; do
  for ((shard = 0; shard < TBMQ_IE_SHARDS; shard++)); do
    IE_SHARD_SUFFIX=""
    ((TBMQ_IE_SHARDS == 1)) || IE_SHARD_SUFFIX="-$shard"
    IE_TOPIC_FILTERS_JSON=$(ie_topic_filters "$IE_SHARD_POSITION" "$shard")
    export IE_SHARD_POSITION IE_SHARD_SUFFIX IE_TOPIC_FILTERS_JSON
    name="app-kafka-ingest-$IE_SHARD_POSITION$IE_SHARD_SUFFIX"
    ie_names+=("$name")
    file="$OUT/app-kafka-integration-$IE_SHARD_POSITION$IE_SHARD_SUFFIX.json"
    render "$DEPLOY_DIR/tbmq/app-kafka-integration.json.tpl" >"$file"
    python3 "$ROOT_DIR/scripts/tbmq_credentials.py" ensure-integration --url "$tbmq_url" \
      --file "$file" --id-file "$OUT/integration-id-$IE_SHARD_POSITION$IE_SHARD_SUFFIX" | sed 's/^/    /'
    python3 "$ROOT_DIR/scripts/tbmq_credentials.py" check-integration --url "$tbmq_url" --file "$file" >/dev/null ||
      die "integration $name differs after the update"
    id=$(<"$OUT/integration-id-$IE_SHARD_POSITION$IE_SHARD_SUFFIX")
    IE_TRIGGERS_YAML+="    - type: kafka
      name: ingest-$IE_SHARD_POSITION$IE_SHARD_SUFFIX
      authenticationRef:
        name: tbmq-kafka-keda
      metadata:
        bootstrapServers: tbmq-kafka-kafka-bootstrap.thingsboard-mqtt-broker.svc:9093
        consumerGroup: ie-msg-consumer-group-${id//-/}
        topic: tbmq.msg.ie.${id//-/}
        lagThreshold: \"$TBMQ_IE_LAG_THRESHOLD\"
        offsetResetPolicy: latest
        allowIdleConsumers: \"false\"
        tls: enable
"
  done
done
# A shard count that shrank leaves integrations whose tunnels are now covered by the new ones; they
# keep consuming until deleted. Pruned after the new set exists, so no tunnel is ever unassigned.
python3 "$ROOT_DIR/scripts/tbmq_credentials.py" prune-integrations --url "$tbmq_url" \
  --prefix app-kafka-ingest- "${ie_names[@]}" | sed 's/^/    /'
unset APP_KAFKA_PASSWORD APP_KAFKA_CA_PEM
if ((TBMQ_IE_SHARDS == 1)); then
  ok "integrations app-kafka-ingest-{start,middle,end}: tunnels/+/sensors/<position>/{detections,health} → iot.mqtt.ingest (SCRAM as tbmq-ie)"
else
  ok "$ie_count integrations app-kafka-ingest-<position>-<0..$((TBMQ_IE_SHARDS - 1))>: $SIM_TUNNELS tunnels split $TBMQ_IE_SHARDS ways by index, up to $(((SIM_TUNNELS + TBMQ_IE_SHARDS - 1) / TBMQ_IE_SHARDS)) topic filters each → iot.mqtt.ingest (SCRAM as tbmq-ie)"
fi

# --- KEDA: integration executors scale on the lag of their integration topics -------------
crd_exists scaledobjects.keda.sh || die "KEDA missing — run: make install-operators"
k -n "$NS" wait kafkauser/keda-tbmq --for=condition=Ready --timeout="${WAIT_TIMEOUT}s" >/dev/null ||
  die "KafkaUser keda-tbmq not ready — run: make install-tbmq-deps"
export IE_TRIGGERS_YAML
render "$DEPLOY_DIR/processing/tbmq-ie-scaler.yaml.tpl" >"$OUT/tbmq-ie-scaler.yaml"
k apply -f "$OUT/tbmq-ie-scaler.yaml" | sed 's/^/    /'
ok "ScaledObject tbmq-integration-executor: ${TBMQ_IE_MIN_REPLICAS}..${TBMQ_IE_MAX_REPLICAS} replicas, lag threshold ${TBMQ_IE_LAG_THRESHOLD} per integration"
