apiVersion: v1
kind: Pod
metadata:
  name: tb-db-setup
spec:
  containers:
    - name: tb-db-setup
      imagePullPolicy: IfNotPresent
      env:
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: tbmq-db-app
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tbmq-db-app
              key: password
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tbmq-valkey
              key: password
