# Application Kafka (Strimzi, KRaft): the domain event backbone, separate from TBMQ's internal Kafka
# so broker internals, retention and consumer lag stay isolated from application workloads.
# Bootstrap: app-kafka-kafka-bootstrap.iot-pipeline.svc:9093 — TLS + SCRAM-SHA-512, ACLs per KafkaUser.
# Reachable only from the pipeline clients below (NetworkPolicy generated by Strimzi, enforced by Cilium).
apiVersion: v1
kind: Namespace
metadata:
  name: iot-pipeline
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: dual-role
  namespace: iot-pipeline
  labels:
    strimzi.io/cluster: app-kafka
spec:
  replicas: ${APP_KAFKA_REPLICAS}
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: ${APP_KAFKA_STORAGE}
        class: local-path
        deleteClaim: false
        kraftMetadata: shared
  # No CPU limit: throttling the request handlers of a broker shows up as produce latency for every
  # client, and this node has threads to spare. The request only has to keep the scheduler honest.
  # Memory request = limit: heap, direct buffers and the page cache charged to the cgroup are not
  # elastic, so overcommitting this pod means an OOM kill under load rather than a slowdown.
  resources:
    requests:
      cpu: ${APP_KAFKA_CPU_REQUEST}
      memory: ${APP_KAFKA_MEMORY_LIMIT}
    limits:
      memory: ${APP_KAFKA_MEMORY_LIMIT}
  jvmOptions:
    -Xms: ${APP_KAFKA_HEAP}
    -Xmx: ${APP_KAFKA_HEAP}
    -XX:
      # Unset, the JVM lets direct memory grow to the heap size: 1536m heap + 1536m direct +
      # metaspace and code cache would cross the 3Gi limit and get the broker OOM killed. The
      # network layer only needs a buffer per connection, so 512m is generous and leaves the rest
      # of the limit for the page cache that actually serves the fetches.
      MaxDirectMemorySize: 512m
---
apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: app-kafka
  namespace: iot-pipeline
spec:
  kafka:
    version: ${KAFKA_VERSION}
    metadataVersion: ${KAFKA_METADATA_VERSION}
    listeners:
      - name: scram
        port: 9093
        type: internal
        tls: true
        authentication:
          type: scram-sha-512
        networkPolicyPeers:
          - podSelector:
              matchLabels:
                app: telemetry-processor
          - podSelector:
              matchLabels:
                app: consensus
          - podSelector:
              matchLabels:
                app: pipeline-viewer      # make watch-topic
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: thingsboard-mqtt-broker
            podSelector:
              matchLabels:
                app: tbmq-integration-executor
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: iot-storage
            podSelector:
              matchLabels:
                app: clickhouse
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: keda
            podSelector:
              matchLabels:
                app: keda-operator
    authorization:
      type: simple
    config:
      auto.create.topics.enable: false
      default.replication.factor: ${APP_KAFKA_REPLICATION_FACTOR}
      min.insync.replicas: ${APP_KAFKA_MIN_ISR}
      offsets.topic.replication.factor: ${APP_KAFKA_REPLICATION_FACTOR}
      transaction.state.log.replication.factor: ${APP_KAFKA_REPLICATION_FACTOR}
      transaction.state.log.min.isr: ${APP_KAFKA_MIN_ISR}
      # Sized for the design target of 300k msg/s of ~250 B records (~75 MB/s per hop) on one broker
      # that shares this node with TBMQ, ClickHouse and the processing pods — not for a cloud fleet.
      # Request handlers: the log append plus one fetch per consumer group (telemetry-processor,
      # consensus, ClickHouse, pipeline-viewer, Kafka Exporter). The fan-out, not the append, is what
      # makes 8 (the default) tight; a thread per core would only add context switches here.
      num.io.threads: 12
      # Socket I/O and the TLS work for listener 9093. 3 (the default) is sized for a small broker;
      # 6 carries 75 MB/s in plus the same volume fanned out to every consumer group.
      num.network.threads: 6
      # Dormant while APP_KAFKA_REPLICAS=1 (nothing to fetch). Set anyway because a second node would
      # otherwise catch up every partition of every topic through a single fetcher thread.
      num.replica.fetchers: 2
      # 1 MiB instead of the default 100 KiB: at 75 MB/s the default holds ~1.3 ms of traffic, so a
      # short GC pause or a busy handler pool already pushes back on TCP. Costs 1 MiB per connection
      # off-heap and stays under this host's net.core.{r,w}mem_max of 4 MiB, above which Linux clamps.
      socket.send.buffer.bytes: 1048576
      socket.receive.buffer.bytes: 1048576
      # Equal on purpose: a follower that cannot fetch a full-size batch in one request stalls the
      # partition. 1 MiB is a batch limit, not a record limit — ~4000 of our 250 B records — so no
      # client has to raise max.partition.fetch.bytes to match.
      message.max.bytes: 1048576
      replica.fetch.max.bytes: 1048576
      # Kafka only deletes closed segments, so a segment as large as a partition's retention.bytes cap
      # would keep ~2x the cap on disk. 256 MiB = 4 segments per 1 GiB cap, rolling every few minutes.
      log.segment.bytes: 268435456
      # None of the producers here compress. LZ4 on ~250 B JSON records is ~3-4x for about 0.2 core at
      # 75 MB/s, which is what keeps the NVMe write rate and the byte caps below manageable; zstd would
      # trade roughly double the CPU for a better ratio. Producers that already send lz4 pay nothing.
      compression.type: lz4
      # retention.bytes is only enforced when the cleaner runs. At 75 MB/s the default 5 min interval
      # lets every partition overshoot its cap by hundreds of MB before anything is deleted.
      log.retention.check.interval.ms: 60000
      # An unclean restart replays the index of every segment; one thread would walk the whole
      # ${APP_KAFKA_STORAGE} volume serially, and NVMe is happy to serve four at once.
      num.recovery.threads.per.data.dir: 4
    # JMX Prometheus exporter on tcp-prometheus/9404 (rules: deploy/observability/strimzi-kafka-metrics.yaml,
    # applied into this namespace by the install step).
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: strimzi-kafka-metrics
          key: kafka-metrics-config.yml
  # Consumer-group lag and topic offsets for alerts and dashboards (Kafka Exporter, 9404).
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 96Mi
  # The TBMQ integration (config stored in TBMQ's database) and ClickHouse hold copies of this CA:
  # a long validity keeps renewals rare. `make install-app-kafka install-tbmq install-storage` re-syncs them.
  clusterCa:
    validityDays: 1825
    renewalDays: 60
  entityOperator:
    topicOperator:
      resources:
        requests:
          cpu: 50m
          memory: 192Mi
        limits:
          memory: 384Mi
    userOperator:
      resources:
        requests:
          cpu: 50m
          memory: 192Mi
        limits:
          memory: 384Mi
