# TBMQ internal Kafka (Strimzi, KRaft). Dedicated to the broker: persistence log and
# inter-node bus. Application workloads get their own Kafka cluster.
# Bootstrap: tbmq-kafka-kafka-bootstrap:9093 — TLS, client certificate required (KafkaUser
# tbmq-broker), reachable only from TBMQ broker and integration executor pods (NetworkPolicy
# generated by Strimzi, enforced by Cilium). No ACLs: dedicated cluster with a single user.
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: dual-role
  namespace: thingsboard-mqtt-broker
  labels:
    strimzi.io/cluster: tbmq-kafka
spec:
  replicas: ${KAFKA_REPLICAS}
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: ${KAFKA_STORAGE}
        class: local-path
        deleteClaim: false
        kraftMetadata: shared
  # No CPU limit: throttling the request handlers of a broker shows up as publish latency for every
  # MQTT client, and this node has threads to spare. The request only has to keep the scheduler honest.
  # Memory request = limit: heap, direct buffers and the page cache charged to the cgroup are not
  # elastic, so overcommitting this pod means an OOM kill under load rather than a slowdown.
  resources:
    requests:
      cpu: ${KAFKA_CPU_REQUEST}
      memory: ${KAFKA_MEMORY_LIMIT}
    limits:
      memory: ${KAFKA_MEMORY_LIMIT}
  jvmOptions:
    -Xms: ${KAFKA_HEAP}
    -Xmx: ${KAFKA_HEAP}
    -XX:
      # Unset, the JVM lets direct memory grow to the heap size: 1536m heap + 1536m direct +
      # metaspace and code cache would cross the 3Gi limit and get the broker OOM killed. The
      # network layer only needs a buffer per connection, so 512m is generous and leaves the rest
      # of the limit for the page cache that actually serves the fetches.
      MaxDirectMemorySize: 512m
---
apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: tbmq-kafka
  namespace: thingsboard-mqtt-broker
spec:
  kafka:
    version: ${KAFKA_VERSION}
    metadataVersion: ${KAFKA_METADATA_VERSION}
    listeners:
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
        networkPolicyPeers:
          - podSelector:
              matchLabels:
                app: tbmq
          - podSelector:
              matchLabels:
                app: tbmq-integration-executor
          - namespaceSelector:              # KEDA scales the integration executor on its consumer lag
              matchLabels:
                kubernetes.io/metadata.name: keda
            podSelector:
              matchLabels:
                app: keda-operator
    config:
      # TBMQ creates its own topics with explicit partitions and replication factor.
      auto.create.topics.enable: false
      default.replication.factor: ${KAFKA_REPLICATION_FACTOR}
      min.insync.replicas: ${KAFKA_MIN_ISR}
      offsets.topic.replication.factor: ${KAFKA_REPLICATION_FACTOR}
      transaction.state.log.replication.factor: ${KAFKA_REPLICATION_FACTOR}
      transaction.state.log.min.isr: ${KAFKA_MIN_ISR}
      # Broker defaults from the upstream TBMQ manifest; TBMQ overrides them per topic.
      log.retention.bytes: 1073741824
      log.segment.bytes: 268435456
      log.retention.ms: 300000
      log.cleanup.policy: delete
      # Sized for the design target of 300k msg/s of ~250 B records (~75 MB/s) on one broker that
      # shares this node with the app Kafka, ClickHouse and the processing pods — not for a fleet.
      # Every published message lands in tbmq.msg.all and is read back by the broker pods, so the
      # request handlers see a produce and a fetch per message.
      num.io.threads: 12
      # Socket I/O and the TLS work for listener 9093, shared by the broker pods and the KEDA-scaled
      # integration executors. 3 (the default) is sized for a small broker.
      num.network.threads: 6
      # Dormant while KAFKA_REPLICAS=1 (nothing to fetch). Set anyway because a second node would
      # otherwise catch up every partition through a single fetcher thread.
      num.replica.fetchers: 2
      # 1 MiB instead of the default 100 KiB: at 75 MB/s the default holds ~1.3 ms of traffic, so a
      # short GC pause or a busy handler pool already pushes back on TCP. Costs 1 MiB per connection
      # off-heap and stays under this host's net.core.{r,w}mem_max of 4 MiB, above which Linux clamps.
      socket.send.buffer.bytes: 1048576
      socket.receive.buffer.bytes: 1048576
      # Equal on purpose: a follower that cannot fetch a full-size batch in one request stalls the
      # partition. 1 MiB is a batch limit, not a record limit, and TBMQ's own clients already allow
      # a 16 MiB partition fetch, so nothing downstream has to change.
      message.max.bytes: 1048576
      replica.fetch.max.bytes: 1048576
      # TBMQ's producers default to compression-type none, so the broker is the only place this can
      # happen: LZ4 on ~250 B payloads is ~3-4x for about 0.2 core at 75 MB/s, and TBMQ's own topic
      # retention.bytes caps then hold that much more. Setting TB_KAFKA_DEFAULT_COMPRESSION_TYPE on
      # the TBMQ pods would be cheaper still, because the payload would also shrink on the wire.
      compression.type: lz4
      # retention.bytes is only enforced when the cleaner runs. At 75 MB/s the default 5 min interval
      # lets every partition overshoot its cap by hundreds of MB before anything is deleted.
      log.retention.check.interval.ms: 60000
      # An unclean restart replays the index of every segment; one thread would walk the whole
      # ${KAFKA_STORAGE} volume serially, and NVMe is happy to serve four at once.
      num.recovery.threads.per.data.dir: 4
    # JMX Prometheus exporter on tcp-prometheus/9404 (rules: deploy/observability/strimzi-kafka-metrics.yaml,
    # applied into this namespace by the install step).
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: strimzi-kafka-metrics
          key: kafka-metrics-config.yml
  # Consumer-group lag and topic offsets for alerts and dashboards (Kafka Exporter, 9404).
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 96Mi
  # User Operator only: issues the client certificate of KafkaUser tbmq-broker (clients CA).
  entityOperator:
    userOperator:
      resources:
        requests:
          cpu: 50m
          memory: 256Mi
        limits:
          memory: 512Mi
---
# Client identity of TBMQ and the integration executor. Secret tbmq-broker: user.p12 +
# user.password (keystore), user.crt/user.key, ca.crt. Strimzi renews it before expiry;
# Reloader then restarts the pods (deploy/tbmq/kustomization.yaml.tpl).
apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: tbmq-broker
  namespace: thingsboard-mqtt-broker
  labels:
    strimzi.io/cluster: tbmq-kafka
spec:
  authentication:
    type: tls
---
# KEDA's view of the internal Kafka: consumer-group lag of the integration executor. Secret keda-tbmq:
# user.crt/user.key used by the TriggerAuthentication in deploy/processing/tbmq-ie-scaler.yaml.tpl.
apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: keda-tbmq
  namespace: thingsboard-mqtt-broker
  labels:
    strimzi.io/cluster: tbmq-kafka
spec:
  authentication:
    type: tls
