#!/usr/bin/env bash
# Shared helpers for install / verify / up scripts. Source, don't execute.
# shellcheck disable=SC2034

set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APPS_DIR="$ROOT_DIR/apps"
DEPLOY_DIR="$ROOT_DIR/deploy"
STATE_DIR="$ROOT_DIR/.state"
GENERATED_DIR="$ROOT_DIR/.generated"

# --- configuration -----------------------------------------------------------
# Precedence: environment > config.local.env > config.env defaults.
load_config() {
  local defaults="$ROOT_DIR/config.env" local_file="$ROOT_DIR/config.local.env"
  local names name
  names=$(grep -oE '\$\{[A-Z0-9_]+:=' "$defaults" | tr -d '${:=' | sort -u)
  declare -A from_env=()
  for name in $names; do
    if [[ -n "${!name+x}" && -n "${!name}" ]]; then from_env[$name]="${!name}"; fi
  done
  if [[ -f "$local_file" ]]; then
    set -a; source "$local_file"; set +a
  fi
  for name in "${!from_env[@]}"; do printf -v "$name" '%s' "${from_env[$name]}"; done
  set -a; source "$defaults"; set +a
  # shellcheck disable=SC2086
  export $names
  CONFIG_NAMES="$names"
}
load_config
export PATH="$TOOLS_BIN_DIR:$PATH"

# TBMQ admin password: configured value, else the one generated by scripts/install/70-tbmq.sh.
if [[ -z "$TBMQ_ADMIN_PASSWORD" && -s "$STATE_DIR/tbmq-admin-password" ]]; then
  TBMQ_ADMIN_PASSWORD=$(<"$STATE_DIR/tbmq-admin-password")
  export TBMQ_ADMIN_PASSWORD
fi

# --- output ------------------------------------------------------------------
if [[ -t 1 && -z "${NO_COLOR:-}" ]]; then
  C_RESET=$'\e[0m' C_BOLD=$'\e[1m' C_DIM=$'\e[2m'
  C_RED=$'\e[31m' C_GREEN=$'\e[32m' C_YELLOW=$'\e[33m' C_BLUE=$'\e[34m' C_CYAN=$'\e[36m'
else
  C_RESET='' C_BOLD='' C_DIM='' C_RED='' C_GREEN='' C_YELLOW='' C_BLUE='' C_CYAN=''
fi

step()  { printf '\n%s==> %s%s\n' "$C_BOLD$C_BLUE" "$*" "$C_RESET"; }
info()  { printf '    %s\n' "$*"; }
ok()    { printf '    %s✔%s %s\n' "$C_GREEN" "$C_RESET" "$*"; }
skip()  { printf '    %s↷ %s%s\n' "$C_DIM" "$*" "$C_RESET"; }
warn()  { printf '    %s!%s %s\n' "$C_YELLOW" "$C_RESET" "$*" >&2; }
die()   { printf '    %s✖ %s%s\n' "$C_RED" "$*" "$C_RESET" >&2; exit 1; }

trap 'rc=$?; printf "%s✖ failed (exit %s) at %s:%s: %s%s\n" "$C_RED" "$rc" "${BASH_SOURCE[0]##*/}" "$LINENO" "$BASH_COMMAND" "$C_RESET" >&2' ERR

# --- generic helpers ---------------------------------------------------------
has() { command -v "$1" >/dev/null 2>&1; }

require() {
  local missing=()
  for c in "$@"; do has "$c" || missing+=("$c"); done
  ((${#missing[@]} == 0)) || die "missing required commands: ${missing[*]} (run: make install-prereqs)"
}

# retry <timeout-seconds> <interval-seconds> <command...>
retry() {
  local timeout=$1 interval=$2; shift 2
  local deadline=$((SECONDS + timeout))
  until "$@" >/dev/null 2>&1; do
    ((SECONDS < deadline)) || return 1
    sleep "$interval"
  done
}

# Run as root, prompting for sudo only when needed.
as_root() {
  if [[ $EUID -eq 0 ]]; then "$@"; else sudo "$@"; fi
}

# Render a template, substituting only ${VARS} that appear in it.
render() {
  local tpl=$1 vars
  vars=$(grep -oE '\$\{[A-Z0-9_]+\}' "$tpl" | sort -u | tr '\n' ' ' || true)
  envsubst "$vars" <"$tpl"
}

# --- kubernetes helpers ------------------------------------------------------
export KUBECONFIG

k() { kubectl --request-timeout=30s "$@"; }

api_ready() { kubectl --request-timeout=5s get --raw /readyz >/dev/null 2>&1; }

wait_api() {
  retry "$WAIT_TIMEOUT" 3 api_ready || die "Kubernetes API not ready after ${WAIT_TIMEOUT}s"
}

crd_exists() { k get crd "$1" >/dev/null 2>&1; }

wait_crd() {
  retry "$WAIT_TIMEOUT" 3 crd_exists "$1" || die "CRD $1 not registered after ${WAIT_TIMEOUT}s"
  k wait --for=condition=Established "crd/$1" --timeout="${WAIT_TIMEOUT}s" >/dev/null
}

# kube_apply <file|->  — kubectl apply that survives immutable StatefulSet fields
# (serviceName, volumeClaimTemplates, ...): the StatefulSet object is recreated
# with --cascade=orphan, so running pods and PVCs (data) are kept and adopted.
kube_apply() {
  local src=$1 tmp err names
  tmp=$(mktemp); err=$(mktemp)
  if [[ "$src" == - ]]; then cat >"$tmp"; else cp "$src" "$tmp"; fi
  if k apply -f "$tmp" 2>"$err" | sed 's/^/    /'; [[ ${PIPESTATUS[0]} -eq 0 ]]; then
    rm -f "$tmp" "$err"; return 0
  fi
  # Two phrasings: "The StatefulSet \"x\" is invalid" when creating, "StatefulSet.apps \"x\" is invalid"
  # when patching an existing one. No match is the normal case for any other error, and grep's exit 1
  # must not abort the script there, or the real message in $err would never be printed.
  names=$(grep -oE '(The StatefulSet|StatefulSet\.apps) "[^"]+" is invalid: spec: Forbidden' "$err" |
    cut -d'"' -f2 | sort -u || true)
  if [[ -z "$names" ]]; then
    cat "$err" >&2; rm -f "$tmp" "$err"; return 1
  fi
  local ns
  for name in $names; do
    ns=$(python3 -c '
import sys
path, name = sys.argv[1:]
for d in open(path).read().split("\n---\n"):
    if "kind: StatefulSet\n" in d and f"\n  name: {name}\n" in d:
        for line in d.splitlines():
            if line.startswith("  namespace: "): print(line.split(": ", 1)[1]); break
        break
' "$tmp" "$name")
    warn "StatefulSet ${ns:-default}/$name has immutable-field changes — recreating (pods and PVCs kept)"
    k -n "${ns:-default}" delete statefulset "$name" --cascade=orphan --wait=true >/dev/null
  done
  k apply -f "$tmp" | sed 's/^/    /'
  rm -f "$tmp" "$err"
}

nodes_ready() { ! k get nodes --no-headers 2>/dev/null | awk '$2 != "Ready"' | grep -q . && k get nodes --no-headers >/dev/null 2>&1; }

# Wait for all nodes Ready; on failure show the kubelet's reason.
ensure_nodes_ready() {
  retry "$WAIT_TIMEOUT" 5 nodes_ready && return 0
  k get nodes -o json | jq -r '.items[] | .metadata.name + ": " +
    ([.status.conditions[] | select(.type == "Ready")][0].message // "unknown")' >&2 || true
  die "nodes still NotReady. If the reason is 'cni plugin not initialized', containerd sees no CNI config in the dir it watches (k3s + flannel-backend=none: /etc/cni/net.d, /opt/cni/bin)"
}

rollout() { # rollout <namespace> <kind/name>
  k -n "$1" rollout status "$2" --timeout="${WAIT_TIMEOUT}s"
}

# Content hash of everything that goes into an app image (apps/<name>/).
app_source_hash() { # app_source_hash <app-dir>
  (cd "$1" && find Dockerfile .dockerignore pyproject.toml config src -type f \
     ! -path '*__pycache__*' ! -name '*.pyc' ! -path '*.egg-info*' -print0 |
   sort -z | xargs -0 sha256sum | sha256sum | cut -c1-12)
}

# Image tag = source hash, so a workload only rolls when the service actually changed.
consensus_image_ref() {
  printf '%s:%s' "$CONSENSUS_IMAGE" "$(app_source_hash "$APPS_DIR/consensus")"
}
processor_image_ref() {
  printf '%s:%s' "$PROCESSOR_IMAGE" "$(app_source_hash "$APPS_DIR/telemetry-processor")"
}

# containerd_has_image <image-ref> — is the image in k3s containerd? Needs root, so it only answers
# when sudo works without a prompt (already authenticated or NOPASSWD); otherwise "unknown" (2).
containerd_has_image() {
  sudo -n true 2>/dev/null || return 2
  sudo -n k3s ctr -n k8s.io images ls -q 2>/dev/null |
    grep -qxE "(docker\.io/library/)?$(printf '%s' "$1" | sed 's/[.[\*^$]/\\&/g')"
}

# import_app_image <image-ref> <app-dir> — docker build → k3s containerd (no registry), skipped when
# this exact ref was imported before (.state/images) and containerd still has it. The record alone is
# not proof: an import that failed halfway leaves pods in ErrImageNeverPull, which the skip would then
# hide on every later run.
import_app_image() {
  local ref=$1 dir=$2 record="$STATE_DIR/images"
  mkdir -p "$STATE_DIR"
  if grep -qxF "$ref" "$record" 2>/dev/null; then
    containerd_has_image "$ref"
    case $? in
      0|2) skip "image $ref already imported"; return 0 ;;
      *) warn "image $ref is recorded as imported but missing from k3s containerd: importing again" ;;
    esac
  fi
  info "building $ref"
  docker build -q -t "$ref" "$dir" >/dev/null
  info "importing $ref into k3s containerd (sudo)"
  docker save "$ref" | as_root k3s ctr -n k8s.io images import - >/dev/null
  # sudo is authenticated at this point, so the check answers for real.
  containerd_has_image "$ref" || [[ $? -eq 2 ]] ||
    die "import of $ref reported success but the image is not in k3s containerd"
  grep -qxF "$ref" "$record" 2>/dev/null || echo "$ref" >>"$record"
  ok "image $ref imported"
}

# CloudNativePG primary of the TBMQ database, and a psql query against it (local socket, peer auth).
tbmq_db_primary() {
  k -n "$TBMQ_NAMESPACE" get pod -l cnpg.io/cluster=tbmq-db,cnpg.io/instanceRole=primary \
    -o jsonpath='{.items[0].metadata.name}'
}
tbmq_db_query() { # tbmq_db_query <sql>
  local pod
  pod=$(tbmq_db_primary) && [[ -n "$pod" ]] || { echo "no tbmq-db primary pod"; return 1; }
  k -n "$TBMQ_NAMESPACE" exec "$pod" -c postgres -- psql -d thingsboard_mqtt_broker -tAc "$1"
}

# Readiness of the operator-managed data services (pods, not just CR conditions: those can be stale
# right after hibernation / paused reconciliation ends).
strimzi_pods_ready() { # strimzi_pods_ready <namespace> <cluster> <replicas>
  local n
  n=$(k -n "$1" get pods -l "strimzi.io/cluster=$2,strimzi.io/broker-role=true" -o json 2>/dev/null |
    jq '[.items[] | select(any(.status.conditions[]?; .type == "Ready" and .status == "True"))] | length') || return 1
  [[ "$n" == "$3" ]] || { echo "$2 pods ready: ${n:-0}/$3"; return 1; }
}
kafka_pods_ready() { strimzi_pods_ready "$TBMQ_NAMESPACE" tbmq-kafka "$KAFKA_REPLICAS"; }
deploy_has_ready() { # deploy_has_ready <namespace> <deployment> — at least one ready replica
  local n
  n=$(k -n "$1" get "deploy/$2" -o jsonpath='{.status.readyReplicas}' 2>/dev/null)
  ((${n:-0} >= 1))
}
postgres_instances_ready() {
  local s
  s=$(k -n "$TBMQ_NAMESPACE" get clusters.postgresql.cnpg.io tbmq-db -o jsonpath='{.status.readyInstances}/{.spec.instances}' 2>/dev/null) || return 1
  [[ "$s" == "$POSTGRES_INSTANCES/$POSTGRES_INSTANCES" ]] || { echo "postgres instances ready: $s"; return 1; }
}

# release_lb_node_ports <namespace> <service> — drop NodePorts that a LoadBalancer Service got
# before allocateLoadBalancerNodePorts=false: the API server keeps already allocated ones.
release_lb_node_ports() {
  local patch
  patch=$(k -n "$1" get svc "$2" -o json | jq -c '
    if .spec.allocateLoadBalancerNodePorts == false then
      [.spec.ports | to_entries[] | select(.value.nodePort != null) | {op: "remove", path: "/spec/ports/\(.key)/nodePort"}]
    else [] end') || return 1
  if [[ "$patch" != "[]" ]]; then
    k -n "$1" patch svc "$2" --type=json -p "$patch" >/dev/null
    ok "released NodePorts of $1/$2"
  fi
}

# --- lifecycle helpers (make down / make up) -----------------------------------
# Strimzi cannot scale a Kafka cluster to zero: pause reconciliation, remove the broker pod sets and
# scale its operator-owned deployments (entity operator, exporter) down. PVCs (deleteClaim: false)
# and the node ids in the KafkaNodePool status are kept.
strimzi_stop() { # strimzi_stop <namespace> <cluster>
  k -n "$1" get "kafka/$2" >/dev/null 2>&1 || return 0
  k -n "$1" annotate kafka "$2" strimzi.io/pause-reconciliation=true --overwrite >/dev/null
  k -n "$1" delete strimzipodset -l "strimzi.io/cluster=$2" --ignore-not-found >/dev/null
  k -n "$1" scale deploy -l "strimzi.io/cluster=$2" --replicas=0 >/dev/null 2>&1 || true
  ok "kafka/$2 paused, pods removed"
}
strimzi_start() { # strimzi_start <namespace> <cluster> — Strimzi recreates the pods on their PVCs
  k -n "$1" get "kafka/$2" >/dev/null 2>&1 || return 0
  if [[ "$(k -n "$1" get kafka "$2" -o jsonpath='{.metadata.annotations.strimzi\.io/pause-reconciliation}')" == true ]]; then
    k -n "$1" annotate kafka "$2" strimzi.io/pause-reconciliation- >/dev/null
    info "kafka/$2: reconciliation resumed"
  fi
}
# KEDA keeps scaling a paused ScaledObject's target to the paused replica count.
keda_pause() { # keda_pause <namespace> <scaledobject>
  k -n "$1" get "scaledobject/$2" >/dev/null 2>&1 || return 0
  k -n "$1" annotate scaledobject "$2" autoscaling.keda.sh/paused-replicas=0 --overwrite >/dev/null
}
keda_resume() { # keda_resume <namespace> <scaledobject>
  k -n "$1" get "scaledobject/$2" >/dev/null 2>&1 || return 0
  k -n "$1" annotate scaledobject "$2" autoscaling.keda.sh/paused-replicas- >/dev/null
}

# A pod gets a copy of the host resolver configuration when it starts, so after the laptop changes
# network the running CoreDNS keeps forwarding to an upstream that no longer answers: every external
# name fails inside the cluster (Grafana's plugin download, Helm chart hooks, image-less fetches).
dns_answers() { # dns_answers <server> <name>  — one A query over UDP, exit 0 when the server answers it
  python3 - "$1" "$2" <<'PY'
import random, socket, struct, sys
server, name = sys.argv[1], sys.argv[2]
query = struct.pack("!HHHHHH", random.randrange(65536), 0x0100, 1, 0, 0, 0)
query += b"".join(bytes([len(p)]) + p.encode() for p in name.split(".")) + b"\0" + struct.pack("!HH", 1, 1)
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.settimeout(5)
try:
    sock.sendto(query, (server, 53))
    answer, _ = sock.recvfrom(4096)
except OSError as e:
    sys.exit(f"{name} via {server}: {e}")
rcode, answers = answer[3] & 0xF, struct.unpack("!H", answer[6:8])[0]
sys.exit(0 if rcode == 0 and answers else f"{name} via {server}: rcode={rcode}, {answers} answers")
PY
}
cluster_dns_ip() {
  k -n kube-system get svc kube-dns -o jsonpath='{.spec.clusterIP}' 2>/dev/null
}
cluster_dns_resolves_externally() { # uses DNS_PROBE_NAME; skipped (exit 0) when the host itself cannot resolve it
  local ip
  ip=$(cluster_dns_ip) && [[ -n "$ip" ]] || return 0
  getent hosts "$DNS_PROBE_NAME" >/dev/null 2>&1 || return 0
  dns_answers "$ip" "$DNS_PROBE_NAME"
}

# A StatefulSet's volumeClaimTemplates are immutable, so changing a PVC size makes every later apply
# fail with "updates to statefulset spec for fields other than ... are forbidden". Recreating the
# StatefulSet with --cascade=orphan keeps its pods running and its PVCs (with their data) in place; the
# new StatefulSet adopts them. The existing PVC keeps its old size — local-path cannot expand a volume
# and never enforced the request anyway, since the volume is a directory on the node disk.
sts_recreate_if_storage_changed() { # sts_recreate_if_storage_changed <namespace> <statefulset> <size>
  local current
  current=$(k -n "$1" get sts "$2" -o jsonpath='{.spec.volumeClaimTemplates[0].spec.resources.requests.storage}' 2>/dev/null) || return 0
  [[ -n "$current" && "$current" != "$3" ]] || return 0
  info "$2: volumeClaimTemplate $current -> $3, recreating the StatefulSet (pods and PVCs are kept)"
  k -n "$1" delete sts "$2" --cascade=orphan >/dev/null
}

helm_revision() { # helm_revision <release> <namespace>  -> revision or 0
  helm status "$1" -n "$2" -o json 2>/dev/null | jq -r '.version // 0' || echo 0
}

# A first install that failed (a --wait timeout, for example) leaves a release with no deployed
# revision, and every later "helm upgrade --install" of it dies with "has no deployed releases".
helm_never_deployed() { # helm_never_deployed <release> <namespace>  — true when the release exists but never deployed
  local history
  history=$(helm history "$1" -n "$2" -o json 2>/dev/null) || return 1
  jq -e 'any(.[]; .status == "deployed")' <<<"$history" >/dev/null 2>&1 && return 1
  warn "release $1 never deployed (last revision: $(jq -r '.[-1].status // "unknown"' <<<"$history")) — uninstalling it first"
}

# Remove such a release so the retry installs it; releases that deployed at least once are left alone.
helm_clear_failed_install() { # helm_clear_failed_install <release> <namespace>
  helm_never_deployed "$1" "$2" || return 0
  helm uninstall "$1" -n "$2" --wait --timeout "${WAIT_TIMEOUT}s" >/dev/null 2>&1 || true
}

# --- verify helpers ----------------------------------------------------------
CHECKS_OK=0 CHECKS_FAILED=0 CHECKS_WARN=0

# check "<description>" <command...>   — command output hidden, exit status decides
check() {
  local desc=$1; shift
  local out
  if out=$("$@" 2>&1); then
    ok "$desc"; CHECKS_OK=$((CHECKS_OK + 1))
  else
    printf '    %s✖%s %s\n' "$C_RED" "$C_RESET" "$desc"
    [[ -n "$out" ]] && printf '%s\n' "$out" | tail -n 3 | sed "s/^/      ${C_DIM}/;s/\$/${C_RESET}/"
    CHECKS_FAILED=$((CHECKS_FAILED + 1))
  fi
}

# soft_check: same as check, but failures only warn
soft_check() {
  local desc=$1; shift
  if "$@" >/dev/null 2>&1; then
    ok "$desc"; CHECKS_OK=$((CHECKS_OK + 1))
  else
    warn "$desc"; CHECKS_WARN=$((CHECKS_WARN + 1))
  fi
}

checks_summary() {
  printf '\n%s%d passed%s, %s%d failed%s, %s%d warnings%s\n' \
    "$C_GREEN" "$CHECKS_OK" "$C_RESET" "$C_RED" "$CHECKS_FAILED" "$C_RESET" "$C_YELLOW" "$CHECKS_WARN" "$C_RESET"
  ((CHECKS_FAILED == 0))
}
